# -*- coding: utf-8 -*-
"""Manipulasi String 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104EMdaR2GAn65Tu5iGt0cB032k2gheLU

Format Specifiers
"""

template = 'Halo,saya %s dari %s'

print (template % ('allyssia okta','yogyakarta'))

"""Fungsi Format"""

template_nama_asal = 'Halo, saya {nama} dari {asal}'
template_makan_minum = 'Saya suka makan{} dan minum {}'

print (template_nama_asal.format (nama='allyssia okta',asal='yogyakarta'))
print (template_makan_minum.format ('nasi goreng','air putih'))

"""String Interpolation/F-"""

nama = 'allyssia okta'
asal = 'yogyakarta'

print (f'Perkenalkan saya {nama} dari {asal}😎')

"""Memecah Sebuah String menjadi list dan sebaliknya"""

alamat = 'surabaya, jawa timur, Indonesia'

print (alamat.split())

print (alamat.split(','))

print (alamat.split(', '))

"""Memecah String menjadi List dan sebaliknnya"""

print('❤️'.join(['Saya','suka','mie ayam']))

print('😘'.join(alamat.split(', ')))

"""Mengubah sebuah string ke bentuk upper"""

print('Halo selamat pagi!'.upper())
print('Halo selamat siang!'.upper())

print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

"""Title case"""

print('daun tidak pernah membencfi angin'.title())
print('LASAKAR PELANGI'.title())

"""sTRING RESERVS"""

print('Indonesia Adalah Negara Kepulauan'.swapcase())
  print('aKu CiNta NegeRI KU'.swapcase())

"""Mencari sebuah kata dari string"""

angka ='12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

"""mereplace kata pada string"""

ibu_kota = 'jakarta'

print(ibu_kota.replace('a','i'))
print(ibu_kota.replace('kar','❤️'))

ibu_kota = 'jakarta'

print(ibu_kota.replace('a',''))

"""Menghitung jumlah karakter"""

paragraf = 'Baru baru ini telah ditemukan sebuah meteor di suat sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')