# -*- coding: utf-8 -*-
"""UTS COMPRO_Allyssia Okta Ramadhani Putri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AJJ_TydMqoFgo0U_nKNBxOsz-XdzT_d-
"""

raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# dipecahkan jadi 2 transaksi karena masih gabung dalam 1 string
x = raw_log.split(";")

# ================= TRANSAKSI 1 =================
x1 = x[0].split("#")

id1 = x1[0].replace("ID:", "").strip()
nama1 = x1[1].replace("NAMA:", "").strip().title()
qty1 = int(x1[2].replace("QTY:", "").strip())
harga1 = int(x1[3].replace("PRICE:", "").strip())

sub1 = qty1 * harga1

# ================= TRANSAKSI 2 =================
x2 = x[1].split("#")

id2 = x2[0].replace("ID:", "").strip()
nama2 = x2[1].replace("NAMA:", "").strip().title()
qty2 = int(x2[2].replace("QTY:", "").strip())
harga2 = int(x2[3].replace("PRICE:", "").strip())

sub2 = qty2 * harga2

# total
total = sub1 + sub2

print("==================================================")
print("         LAPORAN HARIAN KEDAI SOU SPACE")
print("==================================================")

print(f"{'MENU':<25}{'QTY':<8}{'HARGA':<10}{'SUBTOTAL'}")
print("--------------------------------------------------")

print(f"{nama1:<25}{qty1:<8}{harga1:<10}{sub1}")
print(f"{nama2:<25}{qty2:<8}{harga2:<10}{sub2}")

print("--------------------------------------------------")

# ini yang sudah diperbaiki
print(f"{'TOTAL PENDAPATAN HARI INI:':<33}Rp {total}")

print("==================================================")